First import the necessary libraries

In [306]:
import pandas as pd
import numpy as np

Now upload the save the dataset into variable

In [307]:
df = pd.read_csv("edu-data.csv")
df.sample(1)

gender NationalITy  ... StudentAbsenceDays Class
280      M        Iraq  ...            Under-7     H

[1 rows x 17 columns]

In [308]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 480 entries, 0 to 479
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   gender                    480 non-null    object
 1   NationalITy               480 non-null    object
 2   PlaceofBirth              480 non-null    object
 3   StageID                   480 non-null    object
 4   GradeID                   480 non-null    object
 5   SectionID                 480 non-null    object
 6   Topic                     480 non-null    object
 7   Semester                  480 non-null    object
 8   Relation                  480 non-null    object
 9   raisedhands               480 non-null    int64 
 10  VisITedResources          480 non-null    int64 
 11  AnnouncementsView         480 non-null    int64 
 12  Discussion                480 non-null    int64 
 13  ParentAnsweringSurvey     480 non-null    object
 14  ParentschoolSatisfaction  

In [309]:
# Now seprating the nominal attrubites and the numeric attrubites
nominal_attr = ["gender" , "NationalITy" , "PlaceofBirth","StageID","GradeID","SectionID","Topic","Semester","Relation","ParentAnsweringSurvey","ParentschoolSatisfaction"
 ,"StudentAbsenceDays", "Class"]

numeric_attr = ["raisedhands", "VisITedResources", "AnnouncementsView", "Discussion"]

In [310]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df[numeric_attr] = scaler.fit_transform(df[numeric_attr])

In [311]:
fetures = df.loc[:,:"StudentAbsenceDays"]
target = df.loc[:,"Class"]

In [312]:
# One got encoding to nominal attrubites becomes numeric
# df_onehot = pd.get_dummies(fetures)
# df_onehot.sample
target.sample()

123    M
Name: Class, dtype: object

In [313]:
# df_onehot.loc[0:,"gender_F":].astype("int64").dtypes
# df_onehot.info()
fetures.sample(1)

gender NationalITy  ... ParentschoolSatisfaction StudentAbsenceDays
26      M          KW  ...                      Bad            Under-7

[1 rows x 16 columns]

In [314]:
replace_gender = {'gender': {'F': 1, 'M': 2}}
replace_nat = {'NationalITy': {'KW': 1, 'lebanon': 2, 'Egypt': 3, 'SaudiArabia': 4,
                               'USA':5,'Jordan': 6, 'venzuela': 7, 'Iran': 8 , 'Tunis': 9 ,
                               'Morocco': 10,'Syria': 11,'Palestine': 12,'Iraq': 13,'Lybia': 14}}

replace_place = {'PlaceofBirth': {'KuwaIT': 1, 'lebanon': 2, 'Egypt': 3, 'SaudiArabia': 4
                                  , 'USA':5,'Jordan': 6, 'venzuela': 7, 'Iran': 8 , 'Tunis': 9 ,
                                  'Morocco': 10,'Syria': 11,'Iraq': 12,'Palestine': 13,'Lybia': 14}}
replace_stage = {'StageID': {'lowerlevel': 1, 'MiddleSchool': 2, 'HighSchool': 3}}
replace_grade = {'GradeID': {'G-02':1,'G-04':2, 'G-05':3,'G-06':4,'G-07':5,'G-08':6,'G-09':7,'G-10':8,'G-11':9,'G-12':10}}
replace_sec = {'SectionID': {'A': 1, 'B': 2, 'C': 3}}
replace_topic = {'Topic': {'Arabic': 1, 'Biology': 2,'Chemistry': 3,
                           'English': 4, 'French':5,'Geology': 6,
                           'History': 7, 'IT': 8 , 'Math': 9 ,
                           'Quran': 10,'Science': 11,'Spanish': 12}}
replace_sems = {'Semester': {'F': 1, 'S': 2}}
replace_rel = {'Relation': {'Father': 1, 'Mum': 2}}
replace_pas = {'ParentAnsweringSurvey': {'Yes': 1, 'No': 2}}
replace_pss = {'ParentschoolSatisfaction': {'Bad': 1, 'Good': 2}}
replace_sad = {'StudentAbsenceDays': {'Above-7': 1, 'Under-7': 2}}

In [315]:
fetures.replace(replace_gender,inplace=True)
fetures.replace(replace_nat,inplace=True)
fetures.replace(replace_place,inplace=True)
fetures.replace(replace_stage,inplace=True)
fetures.replace(replace_grade,inplace=True)
fetures.replace(replace_sec,inplace=True)
fetures.replace(replace_topic,inplace=True)
fetures.replace(replace_sems,inplace=True)
fetures.replace(replace_rel,inplace=True)
fetures.replace(replace_pas,inplace=True)
fetures.replace(replace_pss,inplace=True)
fetures.replace(replace_sad,inplace=True)

In [316]:
fetures.sample(1)

gender  NationalITy  ...  ParentschoolSatisfaction  StudentAbsenceDays
174       1            6  ...                         1                   1

[1 rows x 16 columns]

In [317]:
replace_class =  {'L': 1, 'M': 2 , 'H':3}
target.replace(replace_class,inplace=True)
target

0      2
1      2
2      1
3      1
4      2
      ..
475    1
476    2
477    2
478    1
479    1
Name: Class, Length: 480, dtype: int64

In [318]:
y = target # labels
X = fetures

In [319]:
# Import train_test_split
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, 
                                                    random_state = 0)
print("Training set has {} samples.".format(X_train.shape[0]))
print("Testing set has {} samples.".format(X_test.shape[0]))

Training set has 384 samples.
Testing set has 96 samples.


In [320]:
from sklearn.metrics import accuracy_score 
from sklearn.metrics import f1_score

In [321]:
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_validate
from sklearn.metrics import make_scorer
from sklearn.metrics import confusion_matrix
models = {}
models['SVC'] = SVC()
models['DecisionTreeClassifier'] = DecisionTreeClassifier()
models['LogisticRegression'] = LogisticRegression(max_iter = 480)

In [322]:
conf_matrix_list_of_arrays = {}
conf_matrix_list_of_arrays["SVC"] = []
conf_matrix_list_of_arrays["DecisionTreeClassifier"] = []
conf_matrix_list_of_arrays["LogisticRegression"] = []
accuracy_results = {"SVC" : {"train":0, "test":0},"DecisionTreeClassifier" : {"train":0, "test":0},"LogisticRegression" : {"train":0, "test":0}}
f1score_results = {"SVC" : {"train":0, "test":0},"DecisionTreeClassifier" : {"train":0, "test":0},"LogisticRegression" : {"train":0, "test":0}}
kf = KFold(n_splits=10)
for model in models:
  for train_index, test_index in kf.split(X):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]
    
    models[model].fit(X_train, y_train)
    predictions_test = models[model].predict(X_test)
    predictions_train = models[model].predict(X_train)
    accuracy_results[model]["train"] += accuracy_score(y_train,predictions_train)
        
    # TODO: Compute accuracy on test set using accuracy_score()
    accuracy_results[model]["test"] += accuracy_score(y_test,predictions_test)
    
    # TODO: Compute F-score on the the first 300 training samples using fbeta_score()
    f1score_results[model]["train"] += f1_score(y_train,predictions_train,average='micro')
    
    # TODO: Compute F-score on the test set which is y_test
    f1score_results[model]["test"] += f1_score(y_test,predictions_test,average='micro')

    conf_matrix = confusion_matrix(y_test, predictions_test)
    conf_matrix_list_of_arrays[model].append(conf_matrix)
  accuracy_results[model]["train"] = accuracy_results[model]["train"] / 10
  accuracy_results[model]["test"] = accuracy_results[model]["test"] / 10
  f1score_results[model]["train"] = f1score_results[model]["train"] / 10
  f1score_results[model]["test"] = f1score_results[model]["test"] / 10
  conf_matrix_list_of_arrays[model] = np.mean(conf_matrix_list_of_arrays[model], axis=0)
  print(model + ":")
  print("Accuracy:" , 'train: ', accuracy_results[model]["train"], '| test: ', accuracy_results[model]["test"])
  print("F1-score:" , 'train: ', f1score_results[model]["train"], '| test: ', f1score_results[model]["test"])
  print("Confusion Matrix:\n" , conf_matrix_list_of_arrays[model])
  print("---------------------------------------------------------")

SVC:
Accuracy: train:  0.6534722222222222 | test:  0.5541666666666668
F1-score: train:  0.6534722222222222 | test:  0.5541666666666668
Confusion Matrix:
 [[ 6.5  5.7  0.5]
 [ 1.9 17.7  1.5]
 [ 0.  11.8  2.4]]
---------------------------------------------------------
DecisionTreeClassifier:
Accuracy: train:  1.0 | test:  0.6
F1-score: train:  1.0 | test:  0.6
Confusion Matrix:
 [[ 9.4  3.1  0.2]
 [ 3.5 11.6  6. ]
 [ 0.2  6.2  7.8]]
---------------------------------------------------------
LogisticRegression:
Accuracy: train:  0.788888888888889 | test:  0.7437499999999999
F1-score: train:  0.788888888888889 | test:  0.7437499999999999
Confusion Matrix:
 [[10.7  2.   0. ]
 [ 2.5 14.6  4. ]
 [ 0.   3.8 10.4]]
---------------------------------------------------------


As shown in the above result, that the SVC is not good at general. However, DecisionTreeClassifier tent to overfit. And the best model is the LogisticRegression

In [323]:
from sklearn.model_selection import GridSearchCV

param_svc = {'C':[1,10,100,1000],'gamma':[1,0.1,0.001,0.0001], 'kernel':['linear','rbf']}

In [324]:
grid_svc = GridSearchCV(SVC(),param_svc)
grid_svc.fit(X_train,y_train)
grid_svc_pred_test = grid_svc.predict(X_test)
grid_svc_pred_train = grid_svc.predict(X_train)

In [325]:
accuracy_results_train = accuracy_score(y_train,grid_svc_pred_train)
        
# TODO: Compute accuracy on test set using accuracy_score()
accuracy_results_test = accuracy_score(y_test,grid_svc_pred_test)

# TODO: Compute F-score on the the first 300 training samples using fbeta_score()
f1score_results_train = f1_score(y_train,grid_svc_pred_train,average='micro')

# TODO: Compute F-score on the test set which is y_test
f1score_results_test= f1_score(y_test,grid_svc_pred_test,average='micro')

In [327]:
print("SVC accuracy after grid search ", "train ->", accuracy_results_train)
print("SVC accuracy after grid search ", "test ->", accuracy_results_test)
print("SVC F1-score after grid search ", "train ->", f1score_results_train)
print("SVC F1-score after grid search ", "test ->", f1score_results_test)

SVC accuracy after grid search  train -> 0.7916666666666666
SVC accuracy after grid search  test -> 0.6875
SVC F1-score after grid search  train -> 0.7916666666666666
SVC F1-score after grid search  test -> 0.6875
